name: Python Task Manager CI


on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  

    steps:
    # 1. katevazei ton kwdika mou
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. katevazei Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # 3. katevazei Flask, pytest
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. run tests
    - name: Run Tests with pytest
      run: |
        pytest